In [1]:
import torch

In [2]:
b=torch.Tensor([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [7]:
b.reshape(shape=(3,4))
print(b)
f=b.T
print(f)
f.reshape(3,4)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])
tensor([[ 1.,  7.],
        [ 2.,  8.],
        [ 3.,  9.],
        [ 4., 10.],
        [ 5., 11.],
        [ 6., 12.]])


tensor([[ 1.,  7.,  2.,  8.],
        [ 3.,  9.,  4., 10.],
        [ 5., 11.,  6., 12.]])